### ISSUE TITLE
make raw "source URLs" into links? 

### ISSUE THREAD

**Issue by JonathanReeve** [mlaa/digitalpedagogy#12]
It seems to me that URLs should generally be the targets of links, and not displayed as plain text in a web page. Compare the following examples: 
- to get started, visit [your Commons portfolio](http://commons.mla.org).
- to get started, visit your Commons portfolio at http://commons.mla.org/portfolio
- to get started, visit your Commons portfolio. The URL is: `http://commons.mla.org/portfolio`

The first of these examples seems the cleanest and most logical to me. An exception to this might be in Works Cited pages, where raw URLs are expected to appear. 

I propose changing entries like this: 

![selection_526](https://cloud.githubusercontent.com/assets/1843676/7008560/f92ebd64-dc61-11e4-8062-28d33eb42161.png)

where there is an unclickable, raw URL, into a cleaner, clickable title, like this: 

![selection_527](https://cloud.githubusercontent.com/assets/1843676/7008583/1ef3a29e-dc62-11e4-8a7b-42f5aab6e7e4.png)

The URL will still exist, of course, it will just be moved from a raw plain text display to the target of a link.

**Comment by chriszarate** [comment]
Adding a label so we can compile issues like this for Editorial when they conduct a formal review.

**Comment by ALGibson** [comment]
Your proposed method of linking text was the style we adopted in LSDA, and so I agree with the principle. I would note, however, that it is difficult for me to agree to this absolutely without seeing the presentation of each link in context. When editing, I might decide to revise, cut, or move copy or the link altogether--or I might decide there is a compelling reason for an explicit URL. The less we do to the text before it comes to copyediting, the better--manipulating copy before editing often confuses contributors about process and decision making. I do understand, however, that your aim is to get things in the best shape for peer review and editing. To that end, I have two questions:  What will I see when I'm editing? I want to see the URL--so I can fact-check and decide what copy to link, how to describe the site linked to, and so on. Second, if we do another book that starts out on GitHub, this seems to me like the type of thing we might ask contributors to do in the submission guidelines, no?

**Comment by JonathanReeve** [comment]
Thanks, Angela, and welcome to GitHub! To answer your questions: 
1. If you edit the text directly, you'd be able to see both the link text and its target URL. It would look like this when you're editing: `[your Commons profile](http://commons.mla.org/profile)`. The square brackets contain the text of the link, and the parentheses contain its URL target. When published, that would end up looking like this: [your Commons profile](http://commons.mla.org/profile). 
2. I agree. I think the sections on markdown and links from the guidelines document in Trac #4357 are a good starting-point for this, and I think we can also expand this into a more formal document that could be of use to future markdown/GitHub based book projects, at the MLA and elsewhere.

**Comment by JonathanReeve** [comment]
Since I feel like the feedback on this one is generally favorable so far, but that this issue hasn't been decided yet, I've put [this change](https://github.com/mlaa/digitalpedagogy/compare/review-stage...mlaa:revise-links?expand=1) in the experimental feature branch [revise-links](https://github.com/mlaa/digitalpedagogy/tree/revise-links), and will provisionally put the test site on that branch. If anyone feels like this change is unwanted, though, I can easily revert the links to the previous style by changing the branch back to `review-stage`.

**Comment by JonathanReeve** [comment]
^ As a stopgap measure, I've changed the branch back to `review-stage`, and turned all the URLs into links, where the link text is the URL, and the link target is the same URL.

**Comment by tlewek** [comment]
Closing. We've been linking all URLs contained in keywords.
